/**
 * Curated Wikimedia Commons photography for place profiles.
 * URLs resolve via Special:FilePath → CDN; open the Commons file page for attribution.
 */

export type PlaceHeroMedia = {
  src: string;
  srcSet: string;
  sizes: string;
  alt: string;
  creditLine: string;
  sourceUrl: string;
};

const CREDIT =
  "Photo: Wikimedia Commons. Open the file page for photographer and license.";

function commonsFile(file: string, width = 1600): string {
  return `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}?width=${width}`;
}

function commonsFilePage(file: string): string {
  return `https://commons.wikimedia.org/wiki/File:${encodeURIComponent(file)}`;
}

function commonsSrcSet(file: string): string {
  return [640, 960, 1280, 1920]
    .map(width => `${commonsFile(file, width)} ${width}w`)
    .join(", ");
}

/** place.id → Commons filename. Landscape-first; file-page credit only. */
const HERO_BY_PLACE_ID: Record<string, { file: string; alt: string }> = {
  "sequim-wa": { file: "D Spit 5783.jpg", alt: "Dungeness Spit reaching into the Strait of Juan de Fuca on a clear rain-shadow day" },
  "monterey-ca": { file: "2016-06-03 USA, CA, Point Lobos DSC 8596 DxO 1.jpg", alt: "Fogbound cypress and rocky Pacific cliffs at Point Lobos on the Monterey fog coast" },
  "black-mountain-nc": { file: "Downtown Black Mountain, North Carolina 01.jpg", alt: "Black Mountain downtown against Blue Ridge foothills" },
  "hood-river-or": { file: "Hood River OR - aerial.jpg", alt: "Hood River, the Columbia, and snow-capped Mount Hood above orchard country" },
  "santa-barbara-ca": { file: "Stearns Wharf - Don Ramey Logan.jpg", alt: "Stearns Wharf and the Santa Ynez Mountains at Santa Barbara" },
  "port-townsend-wa": { file: "Adventuress Schooner Port Townsend Marina , Washington State.jpg", alt: "Port Townsend marina and wooden-boat waterfront on the Olympic rain shadow edge" },
  "tucson-az": { file: "Saguaro National Park East, Arizona, USA 2024 3.jpg", alt: "Saguaro cactus forest and desert hills east of Tucson" },
  "portal-az": { file: "Echo Canyon Trail, Chiricahua National Monument, Willcox, AZ.jpg", alt: "Hoodoo canyon along Echo Canyon in the Chiricahua sky island" },
  "flagstaff-az": { file: "San Francisco Peaks Christmas Day 2010.jpg", alt: "Snowy San Francisco Peaks above Flagstaff's ponderosa country" },
  "sedona-az": { file: "Cathedral Rock - Sedona AZ-1.jpg", alt: "Cathedral Rock at sunset in Sedona's red-rock country" },
  "santa-fe-nm": { file: "Palace of the Governors.jpg", alt: "Adobe Palace of the Governors and plaza light in Santa Fe" },
  "taos-nm": { file: "Taos_Pueblo.jpg", alt: "Multi-story adobe buildings at Taos Pueblo beneath the Sangre de Cristo" },
  "marfa-tx": { file: "The Chinati Foundation La Fundación Chinati, Marfa, Texas 06.JPG", alt: "Donald Judd concrete works on the high-desert grassland at Chinati in Marfa" },
  "key-west-fl": { file: "Sunset Key and Sailboats, Florida, 2025.jpg", alt: "Turquoise water and sailboats off Sunset Key at the end of the Florida Keys" },
  "charleston-sc": { file: "Rainbow Row Charleston July 2024 1.jpg", alt: "Rainbow Row's pastel houses along Charleston's harbor streets" },
  "banff-ab": { file: "1 moraine lake pano 2019.jpg", alt: "Moraine Lake's turquoise water and the Valley of the Ten Peaks" },
  "victoria-bc": { file: "View from Malahat lookout 1.jpg", alt: "Southern Vancouver Island water and hills near Victoria's rain-shadow coast" },
  "qualicum-bc": { file: "Qualicum Beach, British Columbia - panoramio.jpg", alt: "Qualicum Beach shoreline on Vancouver Island's drier east side" },
  "oaxaca-mx": { file: "Aspecto de Monte Albán, Oaxaca.jpg", alt: "Monte Albán's highland ruins above Oaxaca de Juárez" },
  "merida-mx": { file: "Centro Cultural Olimpo, Mérida, Yucatán Junio 2024.jpg", alt: "Night-lit colonial arcade of the Olimpo cultural centre on Mérida's Plaza Grande" },
  "guanajuato-mx": { file: "Guanajuato 2018 06.jpg", alt: "Colourful hillside cityscape of Guanajuato" },
  "san-miguel-de-allende-mx": { file: "PanoramaSanMiguelSW 01.jpg", alt: "Colonial rooftops and Parroquia spires of San Miguel de Allende on the Bajío highland" },
  "bacalar-mx": { file: "Laguna de Bacalar, México, 2025-12-16, DD 25-27 HDR.jpg", alt: "Sunset palapa over Laguna de Bacalar's still lagoon on the Yucatán Caribbean" },
  "puerto-vallarta-mx": { file: "Playa de Los Muertos.jpg", alt: "Los Muertos Beach and bay light at Puerto Vallarta" },
  "osoyoos-bc": { file: "Osoyoos BC 2008.jpg", alt: "Osoyoos Lake in the dry South Okanagan pocket-desert valley" },
  "lethbridge-ab": { file: "Oldman River at Indian Battle Park - October 2012 - panoramio.jpg", alt: "Oldman River coulees and the High Level Bridge at Lethbridge, Alberta" },
  "tofino-bc": { file: "Long beach Tofino Ucluelet British Columbia Canada 2.jpg", alt: "Pacific swell and driftwood beach on the Tofino–Ucluelet outer coast" },
  "tofino-ucluelet-corridor": { file: "Long beach Tofino Ucluelet British Columbia Canada 2.jpg", alt: "Long Beach sand and surf between Tofino and Ucluelet" },
  "wolfville-ns": { file: "Cape Blomidon-mid-day.jpg", alt: "Cape Blomidon above the Annapolis Valley near Wolfville" },
  "niagara-on-the-lake": { file: "Grapevines in Niagara-on-the-Lake.jpg", alt: "Lake-plain vineyards at Niagara-on-the-Lake" },
  "atlin-lake-bc": { file: "ATLIN, BRITISH COLUMBIA.jpg", alt: "Atlin settlement beside the long glacial lake in northwestern British Columbia" },
  "fernie-elk-valley-bc": { file: "Three Sisters from Police Creek.jpg", alt: "Fernie's Three Sisters peaks rising above the Elk Valley" },
  "sunshine-coast-bc": { file: "Sechelt Inlet Sunset (2751310034).jpg", alt: "Sunset over Sechelt Inlet on British Columbia's Sunshine Coast" },
  "salt-spring-bc": { file: "Saltspring Island.jpg", alt: "Salt Spring Island shoreline and Gulf Islands light" },
  "summerland-bc": { file: "Lake Okanagan - Summerland - panoramio.jpg", alt: "Okanagan Lake benches and orchards at Summerland" },
  "grand-manan-nb": { file: "Swallowtail Lighthouse and Pettes Cove.jpg", alt: "Swallowtail Lighthouse and Fundy water on Grand Manan" },
  "creston-bc": { file: "Duck Lake and Kootenay Lake aerial.jpg", alt: "Creston Valley farmland meeting Duck Lake and snowy Kootenay ranges" },
  "penticton-bc": { file: "Penticton, BC - Okanagan Lake Dam 01.jpg", alt: "Okanagan Lake at Penticton in the South Okanagan trench" },
  "kamloops-bc": { file: "Kamloops summer sunset (52782962539).jpg", alt: "Summer sunset over the dry Thompson country at Kamloops" },
  "nelson-bc": { file: "Kootenay Lake at Nelson, BC, Canada (54881215708).jpg", alt: "Kootenay Lake below Nelson in the West Kootenays" },
  "revelstoke-bc": { file: "View of Lake Revelstoke from Mount Revelstoke National Park 20240825 1.jpg", alt: "Lake Revelstoke from the Columbia Mountains snow belt" },
  "prince-rupert-bc": { file: "Prince Rupert harbour 4.jpg", alt: "Prince Rupert harbour on the very wet North Coast" },
  "st-johns-nl": { file: "St. John's Harbour - St. John's, Newfoundland 2019-08-08.jpg", alt: "St. John's harbour and steep streets on the Avalon Peninsula" },
  "whitehorse-yt": { file: "Cañón Miles, Yukón, Canadá, 2017-08-26, DD 130-132 PAN.jpg", alt: "Miles Canyon on the Yukon River at Whitehorse" },
  "yellowknife-nt": { file: "Great Slave Lake in Yellowknife.jpg", alt: "Great Slave Lake shore at Yellowknife" },
  "churchill-mb": { file: "Polar Bears - Churchill, Manitoba (39489485710).jpg", alt: "Hudson Bay tundra and polar-bear country near Churchill" },
  "iqaluit-nu": { file: "Iqaluit, Nunavut.jpg", alt: "Iqaluit waterfront on Frobisher Bay in the eastern Arctic" },
  "haida-gwaii-bc": { file: "Gwaii Haanas (28210876994).jpg", alt: "Coastal forest and water in Gwaii Haanas on Haida Gwaii" },
  "kelowna-bc": { file: "Okanagan Lake, Kelowna, BC, Canada.jpg", alt: "Okanagan Lake benches and water at Kelowna" },
  "squamish-bc": { file: "Howe Sound, Squamish.jpg", alt: "Howe Sound fjord water and mountains at Squamish" },
  "halifax-ns": { file: "Halifax Harbour Sunset Skyline, Nova Scotia (24237034620).jpg", alt: "Halifax harbour skyline at sunset" },
  "charlottetown-pei": { file: "Charlottetown, PEI skyline.jpg", alt: "Charlottetown waterfront skyline on Prince Edward Island" },
  "dawson-city-yt": { file: "Quinta Avenida, Dawson City, Yukón, Canadá, 2017-08-27, DD 30.jpg", alt: "Colourful Klondike-era storefronts on Fifth Avenue in Dawson City beneath northern hills" },
  "baie-saint-paul-qc": { file: "Baie St-Paul (Charlevoix-QC)-Vue de la baie à partir du belvédaire Est-2014-07-21.jpg", alt: "Charlevoix bay, tidal flats, and hills from the eastern lookout at Baie-Saint-Paul" },
  "twillingate-nl": { file: "Lonely Road - Back Harbour - Twillingate - Newfoundlad.JPG", alt: "A harbour road meeting the sea at Twillingate on Newfoundland's iceberg coast" },
  "sutton-qc": { file: "View at Mont SUTTON.jpg", alt: "Snow-covered Eastern Townships ridges from Mont Sutton in winter" },
  "morden-mb": { file: "Pembina Valley Provincial Park fall colours.jpg", alt: "Autumn forest across the Pembina Valley escarpment near Morden, Manitoba" },
  "pincher-creek-ab": { file: "The Rockies from the East, S of Pincher Creek (15438109914).jpg", alt: "Rocky Mountain front from the east near Pincher Creek" },
  "thunder-bay-on": { file: "Sleeping Giant Provincial Park Cliffs - Amethyst Harbour - Ontario - Canada in Autumn.jpg", alt: "Autumn cliffs over Lake Superior in Sleeping Giant Provincial Park near Thunder Bay" },
  "gaspe-qc": { file: "Rocher Percé – Percé, QC – (2018-07-19).jpg", alt: "Percé Rock at the Gaspé Peninsula tip in the Gulf of St. Lawrence" },
  "san-cristobal-mx": { file: "Panorama coleta.JPG", alt: "Red-tile highland rooftops and parish church of San Cristóbal de las Casas" },
  "cuernavaca-mx": { file: "Jardines 042.jpg", alt: "Manicured garden paths and hedges in Cuernavaca's eternal-spring climate" },
  "valle-de-bravo-mx": { file: "Valle de Bravo.jpg", alt: "Valle de Bravo town and pine slopes above Lake Avándaro" },
  "morelia-mx": { file: "Morelia panorama DSC 0400 ed AD.jpg", alt: "Morelia's colonial core on the Michoacán highland" },
  "zacatecas-mx": { file: "La bufa de Zacatecas de noche.JPG", alt: "Cerro de la Bufa above Zacatecas in the northern highlands" },
  "la-paz-mx": { file: "Malecón de La Paz 2025 02.jpg", alt: "La Paz malecón on the Sea of Cortez" },
  "puerto-escondido-mx": { file: "Surf at Sunset - Zicatela Beach - Puerto Escondido - Oaxaca - Mexico (6533419239).jpg", alt: "Pacific sunset surf rolling onto Zicatela Beach at Puerto Escondido" },
  "palenque-mx": { file: "PalenquePalms2020.jpg", alt: "Palenque temples rising from Lacandon jungle palms" },
  "taxco-mx": { file: "2013-12-25 Panorama Taxco de Alarcón anagoria.JPG", alt: "White hillside town of Taxco in the Sierra Madre del Sur" },
  "puebla-mx": { file: "Popocatépetl desde Puebla 02.jpg", alt: "Popocatépetl rising beyond the Puebla highland" },
  "queretaro-mx": { file: "Acueducto 20170917p3.jpg", alt: "Historic aqueduct of Santiago de Querétaro on the Bajío plateau" },
  "ajijic-lake-chapala-mx": { file: "Ajijic Malecon Sunset.jpg", alt: "Lake Chapala malecón sunset near Ajijic" },
  "mazatlan-mx": { file: "Mazatlán Lighthouse at Dawn - panoramio.jpg", alt: "Mazatlán lighthouse and Pacific dawn on the tropical coast" },
  "campeche-mx": { file: "Malecón de Campeche, Campeche, Mexico.jpg", alt: "Palm-lined malecón and Gulf water on Campeche's tropical limestone coast" },
  "patzcuaro-mx": { file: "Lago de Pátzcuaro en Michoacán.jpg", alt: "Lake Pátzcuaro and surrounding Meseta Tarasca highlands" },
  "valle-guadalupe-mx": { file: "L.A. Cetto Winery and Vineyards - Valle de Guadalupe - Outside Ensenada, BC - Mexico - 01 (6778851318).jpg", alt: "Vineyard rows and hills in Valle de Guadalupe on Baja's Mediterranean-climate coast" },
  "xilitla-mx": { file: "Las Pozas, Xilitla (7159081639).jpg", alt: "Las Pozas pools and cloud-forest vegetation at Xilitla" },
  "real-catorce-mx": { file: "Panorámica de Real de Catorce.jpg", alt: "Real de Catorce high-desert mining town in the Sierra de Catorce" },
  "creel-mx": { file: "El Divisadero Chihuahua - panoramio.jpg", alt: "Copper Canyon rim country above Creel" },
  "monterrey-mx": { file: "View of Monterrey (2015).jpg", alt: "Cerro de la Silla rising above Monterrey" },
  "tapalpa-mx": { file: "Templo de la Inmaculada Concepción Tapalpa 1.JPG", alt: "Brick parish church and pine-plateau plaza in Tapalpa, Jalisco" },
  "alamos-mx": { file: "Alamos tarde lluviosa.JPG", alt: "Rain-dark monsoon sky over colonial streets and the church tower in Álamos, Sonora" },
  "xalapa-mx": { file: "Vista del Pico de Orizaba desde Parque Juárez 08.jpg", alt: "Snow-capped Pico de Orizaba seen from Parque Juárez in highland Xalapa" },
  "coatepec-mx": { file: "Arcoiris completo en Coatepec, Veracruz, México.png", alt: "Full rainbow over Coatepec in Veracruz coffee-cloud country" },
  "death-valley-ca": { file: "Morning at Zabriskie Point, Death Valley2.jpg", alt: "Morning light on the badlands of Zabriskie Point in Death Valley" },
  "cannon-beach-or": { file: "Cannon Beach October 2019 001.jpg", alt: "Haystack Rock and the Needles rising from Cannon Beach on the Oregon coast" },
  "new-orleans-la": { file: "Jackson Square New Orleans.jpg", alt: "Jackson Square and St. Louis Cathedral in New Orleans" },
  "bar-harbor-me": { file: "Cadillac Mountain August 2016.jpg", alt: "Cadillac Mountain granite and Atlantic light above Bar Harbor" },
  "asheville-nc": { file: "Blue Ridge Mountains - Asheville.jpg", alt: "Blue Ridge front above Asheville" },
  "boulder-co": { file: "Flatirons Sunrise.jpg", alt: "Sunrise light on the Flatirons above Boulder" },
  "moab-ut": { file: "Delicate Arch, Arches National Park (15468451289).jpg", alt: "Delicate Arch sandstone with the La Sal Mountains beyond Moab" },
  "jackson-wy": { file: "Grand Teton from the Snake River Overlook.jpg", alt: "Grand Teton rising above the Snake River in Jackson Hole" },
  "honolulu-hi": { file: "View towards Diamond Head from Waikiki (5216373638).jpg", alt: "Diamond Head from Waikiki on Oʻahu's leeward shore" },
  "anchorage-ak": { file: "Chugach mountains over Anchorage rooftops.jpg", alt: "Chugach front rising over Anchorage rooftops" },
  "napa-ca": { file: "Schramsberg Vineyards, July 2019-7579+7580.jpg", alt: "Napa Valley vineyards in California's marine-moderated wine country" },
  "palm-springs-ca": { file: "San Jacinto Mountains - Palm Springs.jpg", alt: "San Jacinto escarpment rising above Palm Springs" },
  "austin-tx": { file: "Downtown Austin Skyline - Lady Bird Lake (54987239041).jpg", alt: "Austin skyline across Lady Bird Lake" },
  "savannah-ga": { file: "Savannah GA USA Forsyth Park fountain.jpg", alt: "Live oaks and the fountain in Savannah's Forsyth Park" },
  "hilo-hi": { file: "Rainbow Falls, Hilo (504333) (23502996901).jpg", alt: "Rainbow Falls in the wet windward country above Hilo Bay" },
  "sitka-ak": { file: "Gavan Hill, Sitka, Alaska May 2013.jpg", alt: "Temperate rainforest slopes of Gavan Hill above Sitka" },
  "valdez-ak": { file: "View of the Worthington Glacier from the Richardson Highway outside of Valdez, Alaska.jpg", alt: "Worthington Glacier descending between green coastal mountains outside Valdez" },
  "fairbanks-ak": { file: "Chena River running through downtown Fairbanks.jpg", alt: "Chena River corridor through Fairbanks in interior Alaska" },
  "nome-ak": { file: "A Fragment of the Sea Ice at the Nome Beach (9511610147).jpg", alt: "Bering Sea ice along the beach at Nome" },
  "ashland-or": { file: "Lithia Park Ashland November 2019 008.jpg", alt: "Lithia Park trees and creek in Ashland's Rogue Valley" },
  "prescott-az": { file: "WatsonLake,US-AZ(11.11).jpg", alt: "Granite Dells and Watson Lake in Arizona's mile-high central highlands" },
  "missoula-mt": { file: "University Mountain from Higgins Avenue, Missoula, MT.jpg", alt: "The M on Mount Sentinel above Missoula's dry-grass Clark Fork valley" },
  "bozeman-mt": { file: "080510 bozeman scenery.jpg", alt: "Bridger-front scenery on the Gallatin Valley at Bozeman" },
  "durango-co": { file: "Animas River just north of downtown Durango, CO.jpg", alt: "Animas River valley just north of Durango" },
  "crested-butte-co": { file: "Crested Butte.jpg", alt: "Crested Butte mountain town in the high Elk Mountains" },
  "leadville-co": { file: ".Mount Elbert Trail.jpg", alt: "Mount Elbert trail country above Leadville, North America's highest city" },
  "cody-wy": { file: "Cody, Wyoming.jpg", alt: "Cody at the eastern gateway to the Absaroka and Yellowstone country" },
  "cloudcroft-nm": { file: "Sacramento Mountains, New Mexico (16260719942).jpg", alt: "Sacramento Mountains forest high above the Tularosa Basin" },
  "logan-ut": { file: "Logan Canyon - Bear River Mountains (Utah) 7-9-2014 9-13-23.JPG", alt: "Craggy limestone walls of Logan Canyon in the Bear River Range of northern Utah" },
  "borrego-springs-ca": { file: "Ansicht der Carrizo Badlands.jpg", alt: "Carrizo Badlands in Anza-Borrego near Borrego Springs" },
  "hood-river-gorge": { file: "Crown Point Vista House - Columbia River Gorge Oregon (35476869624).jpg", alt: "Columbia River Gorge from Crown Point and the Vista House" },
  "winthrop-wa": { file: "Winthrop (29822638388).jpg", alt: "Winthrop in the Methow Valley rain shadow of the North Cascades" },
  "brookings-or": { file: "Sea Stacks at Harris Beach State Park near Brookings, Oregon.jpg", alt: "Sea stacks and Pacific surf at Harris Beach near Brookings on the southern Oregon coast" },
  "joseph-or": { file: "Hurwal Divide and Chief Joseph Mountain.jpg", alt: "Wallowa Mountains above Joseph, Oregon" },
  "stanley-id": { file: "McGown Peak reflected on Stanley Lake, Idaho.jpg", alt: "McGown Peak reflected in Stanley Lake in the Sawtooths" },
  "mount-washington-nh": { file: "White Mountains 12 30 09 81.jpg", alt: "Presidential Range and Mount Washington in the White Mountains" },
  "ely-mn": { file: "The Boundary Waters, Minnesota.jpg", alt: "Boundary Waters lakes and boreal forest near Ely, Minnesota" },
  "nags-head-nc": { file: "Jockey's Ridge State Park Nags Head 19.jpg", alt: "Wind-sculpted dunes and maritime scrub at Jockey's Ridge in Nags Head" },
  "lubbock-tx": { file: "Lubbock, Texas skyline.jpg", alt: "Lubbock skyline on the High Plains of West Texas" },
  "ojai-ca": { file: "Ojai, California (20961845073).jpg", alt: "Ojai Valley orchards and mountains" },
  "corpus-christi-tx": { file: "Corpus Christi skyline.jpg", alt: "Corpus Christi skyline against the Laguna Madre and Gulf" },
  "bismarck-nd": { file: "North Dakota State Capitol 02.jpg", alt: "North Dakota capitol tower above the Missouri River plains at Bismarck" },
  "morgantown-wv": { file: "City of Morgantown from the west side of the Monongahela River, May 2012.jpg", alt: "Morgantown across the Monongahela on the Appalachian Plateau" },
  "cape-may-nj": { file: "Cape May Lighthouse September 2020 002.jpg", alt: "Cape May Lighthouse at the Atlantic tip of New Jersey" },
  "block-island-ri": { file: "Mohegan Bluff's at Block Island IMG 1094.JPG", alt: "Mohegan Bluffs and Atlantic water off Block Island" },
  "spearfish-sd": { file: "Roughlock Falls, Black Hills (52944723151).jpg", alt: "Mossy cascades at Roughlock Falls in Spearfish Canyon, northern Black Hills" },
  "mobile-al": { file: "Mobile, Alabama skyline.jpg", alt: "Mobile skyline and river delta on Alabama's Gulf maritime coast" },
  "naples-fl": { file: "Gulf of Mexico from Naples FL pier.jpg", alt: "Gulf of Mexico from the Naples fishing pier" },
  "des-moines-ia": { file: "Des Moines skyline (55298344286).jpg", alt: "Des Moines skyline from the Capitol terrace on the Iowa prairie river" },
  "washington-dc": { file: "Lincoln Memorial Reflecting Pool 20240601.jpg", alt: "Lincoln Memorial and the Reflecting Pool on the National Mall" },
  "rapid-city-sd": { file: "Dean Franklin - 06.04.03 Mount Rushmore Monument (by-sa).jpg", alt: "Mount Rushmore in the eastern Black Hills above Rapid City country" },
  "roswell-nm": { file: "Bottomless Lakes State Park (3902035251).jpg", alt: "Desert sinkhole lake and arid plains at Bottomless Lakes near Roswell" },
  "page-az": { file: "Grand Canyon Horseshoe Bend.jpg", alt: "Horseshoe Bend of the Colorado River below Page, Arizona" },
  "lone-pine-ca": { file: "View of Mt. Whitney from Lone Pine, CA.jpg", alt: "Mount Whitney rising above Lone Pine and the Owens Valley" },
  "leavenworth-wa": { file: "Between Perfection and Leprechaun Lakes, Enchantments (11 October 2024).jpg", alt: "Alpine lakes in the Enchantments above Leavenworth" },
  "friday-harbor-wa": { file: "Aerial Friday Harbor Washington August 2009.jpg", alt: "Aerial view of Friday Harbor marina and San Juan Island's rain-shadow inland sea" },
  "point-reyes-ca": { file: "Chimney Rock Trail Point Reyes December 2016 panorama 2.jpg", alt: "Pacific headlands and surf along the Chimney Rock Trail at Point Reyes" },
  "truckee-ca": { file: "DSC02806-8 panorama, South Lake Tahoe, Nevada, USA (6958076412).jpg", alt: "Lake Tahoe high-Sierra water near the Truckee basin" },
  "mammoth-lakes-ca": { file: "Convict Lake 39.jpg", alt: "Convict Lake in the Eastern Sierra high country near Mammoth" },
  "forks-wa": { file: "Hoh Rain Forest Olympic June 2018 002.jpg", alt: "Hoh Rain Forest moss and Sitka spruce near Forks" },
  "astoria-or": { file: "Astoria-Megler Bridge.jpg", alt: "Astoria–Megler Bridge spanning the Columbia River mouth" },
  "eureka-ca": { file: "Samoa Beach near Eureka, California.jpg", alt: "Samoa Beach dunes and Pacific fog-belt light near Eureka" },
  "spokane-wa": { file: "Spokane Washington Spokane River.jpg", alt: "Sunset over the Spokane River and Monroe Street Bridge in inland Washington" },
  "buffalo-ny": { file: "Buffalo December 2024 40 (Buffalo Harbor State Park).jpg", alt: "Buffalo Harbor on Lake Erie in winter light" },
  "ithaca-ny": { file: "Footbridge to Taughannock Falls lower lookout, seen from Overlook Viewpoint 01.jpg", alt: "Autumn gorge and rocky creek at Taughannock Falls near Ithaca" },
  "traverse-city-mi": { file: "West Grand Traverse Bay (Suttons Bay Township).jpg", alt: "West Grand Traverse Bay in the Leelanau fruit belt" },
  "gatlinburg-tn": { file: "Meadow in the Smoky Mountains (41923p).jpg", alt: "Mountain meadow in the Great Smokies above Gatlinburg" },
  "duluth-mn": { file: "Snowy Park Point Boardwalk - Lake Superior, Duluth, Minnesota (31162083803).jpg", alt: "Snowy Park Point boardwalk on Lake Superior at Duluth" },
  "chattanooga-tn": { file: "Market Street and Walnut Street Bridges, across the Tennessee River, Chattanooga, Tennessee (67681).jpg", alt: "Tennessee River bridges at Chattanooga beneath Lookout Mountain" },
  "burlington-vt": { file: "Burlington, Vermont Waterfront (30308921845).jpg", alt: "Burlington waterfront on Lake Champlain" },
  "boone-nc": { file: "Grandfather Mountain from Grandfather Overlook, Oct 2016.jpg", alt: "Grandfather Mountain from the High Country overlook near Boone" },
  "wenatchee-wa": { file: "Views of Wenatchee from Squilchuck Road in April (47649).jpg", alt: "Wenatchee and the Columbia River from the Squilchuck benches" },
  "yuma-az": { file: "Algodones Dunes kz02.jpg", alt: "Algodones Dunes sand sea on the Sonoran edge near Yuma" },
  "huachuca-az": { file: "Huachuca Mountains after Monsoon.jpg", alt: "Huachuca sky-island slopes after a monsoon storm" },
  "bishop-ca": { file: "Downtown Bishop with the Sierra Nevada Mountains in the background.jpg", alt: "Bishop on the Owens Valley floor with the Sierra Nevada rising behind" },
  "silver-city-nm": { file: "Overlooking downtown Silver City from Boston Hill.jpg", alt: "Silver City rooftops and hills from Boston Hill in southwest New Mexico" },
  "driggs-id": { file: "Grand Teton - panoramio.jpg", alt: "Grand Teton from the Idaho side of Teton Valley" },
  "grand-marais-mn": { file: "BreakwaterGrandMaraisMN.jpg", alt: "Grand Marais breakwater on the Lake Superior north shore" },
  "highlands-nc": { file: "The town of Highlands, North Carolina, in Macon County 03.jpg", alt: "Highlands town and Southern Appalachian cloud-forest ridges" },
  "grand-marais-mi": { file: "Grand Marais, MI (Aug 2016).jpg", alt: "Grand Marais on Michigan's Upper Peninsula Lake Superior shore" },
  "apalachicola-fl": { file: "Apalachicola FL Gorrie Bridge Apalachicola Bay01.jpg", alt: "Open Apalachicola Bay water and grassy shore on Florida's Forgotten Coast" },
  "santa-cruz-felton-ca": { file: "Henry Cowell Redwoods State Park 05.jpg", alt: "Coast redwoods in Henry Cowell grove around Felton" },
  "ellensburg-wa": { file: "West of Ellensburg (9564355777).jpg", alt: "Kittitas Valley benches and sky west of Ellensburg, Washington" },
  "fort-davis-tx": { file: "A scenic view from outside Fort Davis, Texas. (24745840379).jpg", alt: "High-desert cottonwoods and volcanic hills outside Fort Davis in the Davis Mountains" },
  "gunnison-co": { file: "Blue Mesa Landscape.jpg", alt: "Blue Mesa Reservoir in Gunnison's high cold-pool country" },
  "canaan-valley-wv": { file: "Flowers of Canaan Valley 2021a.jpg", alt: "Summer wildflowers across Canaan Valley in the West Virginia highlands" },
  "redfield-ny": { file: "North Branch Salmon River, Tug Hill region, NY (winter).JPG", alt: "Winter river ice on Tug Hill, the lake-effect snow engine of upstate New York" },
  "syracuse-ny": { file: "Syracuse, New York skyline (cropped).jpg", alt: "Syracuse skyline in the Ontario lake-effect belt of central New York" },
  "marquette-mi": { file: "Lake Superior from Marquette (8741871552).jpg", alt: "Lake Superior from Marquette on the Upper Peninsula shore" },
  "houghton-mi": { file: "Houghton 2019 Aerial.jpg", alt: "Aerial view of Houghton on the Keweenaw waterway" },
  "viroqua-wi": { file: "Driftless Area - panoramio - Corey Coyle.jpg", alt: "Forested bluff and winding road in Wisconsin's Driftless hill country near Viroqua" },
  "south-padre-tx": { file: "South Padre Island beach panorama.jpg", alt: "South Padre Island beach and Gulf water on the Texas coast" },
  "valentine-ne": { file: "Fort Niobrara National Wildlife Refuge (51535322291).jpg", alt: "Niobrara River valley grasslands and pine breaks near Valentine, Nebraska" },
  "loess-hills-ia": { file: "Loess Hills 0628.jpg", alt: "Loess Hills bluffs rising from the Missouri River plains" },
  "flint-hills-ks": { file: "Flint Hills - 51424666164.jpg", alt: "Rolling tallgrass prairie and grazing country in the Flint Hills of Kansas" },
  "eureka-springs-ar": { file: "Downtown Eureka Springs at Main St.jpg", alt: "Historic stone downtown of Eureka Springs on the Ozark escarpment" },
  "medford-or": { file: "Upper Table Rock 1.jpg", alt: "Upper Table Rock mesa above the Rogue Valley near Medford, Oregon" },
  "international-falls-mn": { file: "Voyageurs rainy lake.JPG", alt: "Rocky pine islands on Rainy Lake in Voyageurs country near International Falls" },
  "erie-pa": { file: "Erie PA skyline from tower observation deck (cropped).jpg", alt: "Erie skyline on the Lake Erie snowbelt shore of Pennsylvania" },
  "paducah-ky": { file: "Confluence of the Ohio and Tennessee Rivers.jpg", alt: "Ohio and Tennessee rivers meeting under summer clouds at Paducah" },
  "port-orford-cape-blanco-or": { file: "Cape Blanco Lighthouse (6) (10846022174).jpg", alt: "Cape Blanco headland and lighthouse on the southern Oregon coast" },
  "klamath-falls-upper-klamath-basin-or": { file: "Klamath Falls (2022).jpg", alt: "Klamath Falls and the Upper Klamath Basin in south-central Oregon" },
  "los-alamos-pajarito-plateau-nm": { file: "Panorama of Valles Caldera, New Mexico (7271433464).jpg", alt: "Valles Caldera grassland bowl above the Pajarito Plateau" },
  "lander-sinks-canyon-wy": { file: "Sinks Canyon State Park (4679266666).jpg", alt: "Sinks Canyon walls and river west of Lander, Wyoming" },
  "mentone-al": { file: "Desoto Falls, AL 8-27-13 (54).jpg", alt: "DeSoto Falls plunging into a rock amphitheater on Lookout Mountain near Mentone" },
  "norfolk-ct": { file: "Norfolk, Connecticut.jpg", alt: "Norfolk village in the northwest Connecticut highlands" },
  "lewes-de": { file: "Cape Henlopen State Park Lewes, DE March 2019.jpg", alt: "Cape Henlopen dunes and Atlantic light at Lewes, Delaware" },
  "clayton-ga": { file: "Aerial of downtown Clayton, Georgia, in Rabun County 05.jpg", alt: "Aerial view of Clayton on the Blue Ridge front in northeast Georgia" },
  "galena-il": { file: "Galena, Illinois.jpg", alt: "Galena's brick townscape in the Driftless Mississippi hills" },
  "beverly-shores-in": { file: "Indiana Sand Dunes - Dunbar Beach on Lake Michigan - Beverly Shores (52886936512).jpg", alt: "Lake Michigan dunes and beach at Beverly Shores" },
  "oakland-md": { file: "Deep Creek Lake State Park in Maryland.jpg", alt: "Autumn forest and rocky shore at Deep Creek Lake near Oakland, Maryland" },
  "pittsfield-ma": { file: "Pittsfield, Massachusetts skyline.jpg", alt: "Pittsfield skyline in the Berkshire hills of western Massachusetts" },
  "ocean-springs-ms": { file: "Shrimpboats.JPG", alt: "Shrimp boats on the Mississippi Sound at Ocean Springs" },
  "eminence-mo": { file: "Junction of Jacks Fork and Current River near Eminence, Missouri (79271).jpg", alt: "Jacks Fork meeting the Current River near Eminence in the Missouri Ozarks" },
  "mount-charleston-nv": { file: "Aerial view of the Spring Mountains, Nevada, December 2023.jpg", alt: "Snow-dusted Spring Mountains rising from the Mojave, including Mount Charleston" },
  "geneva-on-the-lake-oh": { file: "Snowy Lake Erie Shoreline at Geneva-on-the-Lake, Ohio - 20220216.jpg", alt: "Snowy Lake Erie shoreline and riprap at Geneva-on-the-Lake in winter" },
  "broken-bow-ok": { file: "Bridge across Broken Bow Lake, OK IMG 8527.JPG", alt: "Misty cypress shoreline and footbridge on Broken Bow Lake in the Ouachita forest" },
  "burkes-garden-va": { file: "Burke's Garden.jpg", alt: "Burkes Garden bowl and surrounding ridges in southwest Virginia" },
  "scottsbluff-ne": { file: "Scotts Bluff National Monument - Nebraska (14439451582).jpg", alt: "Scotts Bluff escarpment above the North Platte plains of western Nebraska" },
  "wilmington-de": { file: "Wilmington, Delaware, USA.jpg", alt: "Wilmington on the Brandywine–Piedmont edge of Delaware" },
  "mystic-ct": { file: "Mystic, Connecticut aerial view.jpg", alt: "Aerial view of Mystic on Fishers Island Sound in Connecticut" },
  "state-college-pa": { file: "Downtown sc.jpg", alt: "Downtown State College in Pennsylvania's Ridge and Valley country" },
  "columbia-sc": { file: "Congaree River, South Carolina.jpg", alt: "Congaree River and Columbia skyline beyond a lush summer treeline" },
  "cypress-hills-sk": { file: "CypressHills1.JPG", alt: "Cypress Hills upland rising above the surrounding Saskatchewan prairie" },
  "leamington-on": { file: "Point Pelee National Park beach, looking north.jpg", alt: "Lake Erie surf and wooded shoreline at Point Pelee near Leamington" },
  "prince-edward-co-on": { file: "Limestone shore at Sandbanks Provincial Park.jpg", alt: "Limestone shore and dunes at Sandbanks in Prince Edward County" },
  "inuvik-nt": { file: "View up Mackenzie River east channel to Inuvik, NT.jpg", alt: "Mackenzie Delta channels looking toward Inuvik" },
  "medicine-hat-ab": { file: "South Saskatchewan near Medicine Hat.jpg", alt: "South Saskatchewan River coulee country near Medicine Hat, Alberta" },
  "zacatlan-de-las-manzanas-mx": { file: "Mirador en Zacatlán de las Manzanas, Puebla 02.jpg", alt: "Highland overlook at Zacatlán de las Manzanas" },
  "todos-santos-mx": { file: "Plaza Todos Santos BCS - panoramio.jpg", alt: "Plaza and desert-oasis townscape of Todos Santos in Baja California Sur" },
  "saltillo-mx": { file: "PLAZA DE ARMAS, SALTILLO COAHUILA - panoramio (3).jpg", alt: "Plaza de Armas and highland light in Saltillo, Coahuila" },
  "cuauhtemoc-mx": { file: "Cuauhtémoc landscape 3.jpg", alt: "Cuauhtémoc on the Chihuahua highland with mesa country on the horizon" },
  "tequila-mx": { file: "Paisaje agaves cerca de Tequila, Jal. 280424 I.jpg", alt: "Blue-agave landscape in the Tequila highland of Jalisco" },
  "mazamitla-mx": { file: "Quiosco en la plaza principal de Mazamitla, Jalisco.jpg", alt: "Plaza and pine-highland townscape of Mazamitla" },
  "la-ventosa-mx": { file: "WindTurbinesLaVentosa.jpg", alt: "Wind turbines across the Isthmus of Tehuantepec gap-wind corridor at La Ventosa" },
  "ensenada-mx": { file: "Private Beach (121492157).jpeg", alt: "Marine-layer fog over Punta Banda's Pacific coast south of Ensenada" },
  "cuatrocienegas-mx": { file: "Poza Azul Cuatro Cienegas.jpg", alt: "Poza Azul turquoise pool in the Cuatro Ciénegas desert basin" },
  "parras-de-la-fuente-mx": { file: "Santo Madero, Parras de la Fuente, Coah.jpg", alt: "White Santo Madero chapel on the rocky hill above the Parras oasis wine valley" },
  "toluca-mx": { file: "Toluca a los pies del nevado.jpg", alt: "Toluca at the foot of the Nevado on the high Mexican volcanic belt" },
  "hermosillo-mx": { file: "HMO (26944081661).jpg", alt: "Cerro de la Campana and Hermosillo spreading across the Sonoran Desert valley" },
  "durango-mx": { file: "Victoria de Durango desde el cerro de Los Remedios.jpg", alt: "Victoria de Durango from Cerro de Los Remedios in the northern highlands" },
  "orizaba-mx": { file: "En las faldas del Pico de Orizaba.jpg", alt: "Pico de Orizaba's slopes above the highland approaches to Orizaba" },
};

export function getPlaceHeroMedia(placeId: string): PlaceHeroMedia | null {
  const row = HERO_BY_PLACE_ID[placeId];
  if (!row) return null;
  return {
    src: commonsFile(row.file),
    srcSet: commonsSrcSet(row.file),
    sizes: "(min-width: 768px) 52rem, calc(100vw - 2rem)",
    alt: row.alt,
    creditLine: CREDIT,
    sourceUrl: commonsFilePage(row.file),
  };
}

export function listPlaceHeroFiles(): ReadonlyArray<{ id: string; file: string }> {
  return Object.entries(HERO_BY_PLACE_ID).map(([id, row]) => ({ id, file: row.file }));
}

export function placeHeroMediaCount(): number {
  return Object.keys(HERO_BY_PLACE_ID).length;
}

/** Static OpenStreetMap map centered on the place (opens in a new tab). */
export function openStreetMapUrl(lat: number, lon: number, zoom = 10): string {
  return `https://www.openstreetmap.org/?mlat=${lat}&mlon=${lon}#map=${zoom}/${lat}/${lon}`;
}
